#!/bin/bash

cat /etc/passwd | grep '/home/' | \
grep -v 'cups\|syslog' | cut -d ':' -f 6 > /tmp/homes.list

while read BASEDIR; do
    rm -rf "$BASEDIR/.config/optgeo/"
    rm -rf "$BASEDIR/Desktop/optgeo-i18n.desktop"
done < /tmp/homes.list