#!/bin/bash

cat /etc/passwd | grep '/home/' | \
grep -v 'cups\|syslog' | cut -d ':' -f 1 > /tmp/homes.list

while read USUARIO; do
	runuser -l $USUARIO -c "mkdir -p /home/$USUARIO/.config/optgeo/"
 	runuser -l $USUARIO -c "cp /tmp/optgeo.ini /home/$USUARIO/.config/optgeo/"

	cp /usr/share/applications/optgeo-i18n.desktop /home/$USUARIO/Desktop/optgeo-i18n.desktop

	runuser -l $USUARIO -c "rm -rf /home/$USUARIO/.cache/"
	if [ -f /usr/bin/lxpanelctl ]; then
		su - $USUARIO -c "lxpanelctl restart"
	fi
done < /tmp/homes.list
